### GET request with a header
GET http://localhost:8080/
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = abBRjEWWe2WXiVKBBwnArjumeRQnnYvakt-iz97zJlXWhOCHC4Ni6n2gHQG6v2W5ZST0nQ2VVHUT-b_38OiXremQFDHutNnk

### GET request with json body
GET http://localhost:8080/csrf-token
Content-Type: application/json