### GET request with a header
GET http://localhost:8080/
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = Yp95Id3TRxRn-kb3O0_Utr8JHr0PkLAVS-m9BXwdVDJbsuieV_pIEbvrJnVKw3LODWLghoY-M4U9ooc4LdiNNBl4ZwVqgo2u

### GET request with json body
GET http://localhost:8080/csrf-token
Content-Type: application/json
